apiVersion: v1
kind: Service
metadata:
  labels:
    app: block-buster
  name: block-buster-service
  namespace: 8-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
<<<<<<< HEAD
    nodePort: 30001
=======
    nodePort: 30008
>>>>>>> fe95025 (Update service.yml)
  selector:
    app: block-buster
    version: 7.8.x
    env: dev
  type: NodePort
