apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAv8YgFzKIJgYY5fwGzdBTVdZq6eZnEenpQnajC2qz4bDvckmfatFFiJMvCnqtsdbouEMxQncqoJu+8hEDG8Y9tqLD2szbOYfwGA9loNUIvycHQcRz/IpKY7r9YTiGEs1+hl28X/tu3szPJt7/uvOX/c0UBIGXG//YrK+nBeAdSmwEoNhhSvXQpJRPbd/n+J5CZlzVYAhwqGVpF7Iiqov9VbVrPcbj3lqB1d+ofWfxYRFQiVCA8E2PlRVySF/GWLp0kYXskTrAxyzr1zgxb4mif1cRqBIjZ/SRIqqir411/VJD8VMiJmwU2YYyzsAF9d7fG087WZGnQiU8/zNl2gzpOtIr2djmh68pDSIPPipDLGkTZzjEqEWqpwmnEo/4KKij886+jkDHh5d3s0l9HEzBVrdNkfqpur7ZjupITRViRrLvSyYrbK5cI46Y6VfW3XPGfK5Fw7UupTBG0jjFZXlm1XXSrP3lJYxS/kyr0UMPE3EtbRYr1yC4PnRj3Eh+IohYGfFyrsmAK+s5aKcCLC98w5Mk0erjERVdg79UWxvrRIjzFinavku7EK1GpspA67lD7UIsAnrPDloJ0UgW/WWK2u6PB4bDKCtytZn5BXCRSanP4FlmX+YsxGFGYBt0zmCCYDtaUelWG9HZVGqx6xztCcuSSl7feXRt7odDB1zCUwOX9crK028nxqqeDPDZj/zZjzMI488EKFcgRVCAGBBSc4QHt0iwMfOiD
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

